### ISSUE TITLE
Incompatibility with events @xstate.microstep of xstate@5.7.1

### ISSUE THREAD

**Issue by Zehir** [statelyai/inspect#20]
Hello there,

Since the new inspection event `@xstate.microstep` in this PR :
https://github.com/statelyai/xstate/pull/4693

Looks like the inspector don't like it because I am getting a lot of errors for it.
```js
Uncaught Error: Invalid inspection event type: @xstate.microstep
    at convertXStateEvent (@statelyai_inspect.js?v=05290a21:3565:17)
    at inspectNext (@statelyai_inspect.js?v=05290a21:3491:38)
```

**Comment by davidkpiano** [comment]
Make sure that you install the latest version of `@statelyai/inspect` - this was recently fixed there.

**Comment by davidkpiano** [comment]
https://github.com/statelyai/inspect/pull/18

**Comment by Zehir** [comment]
Thanks @davidkpiano but looks like it's an publish issue, the @statelyai/inspect@0.2.4 was never published

**Comment by davidkpiano** [comment]
Sorry, this should now be published!
